// Conventional commits with og's own scopes. Scopes follow the plan's areas.
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', [
      'build',
      'chore',
      'ci',
      'design',
      'docs',
      'feat',
      'fix',
      'perf',
      'refactor',
      'revert',
      'style',
      'test',
    ]],
    'scope-enum': [2, 'always', [
      // infrastructure
      'agents',
      'api',
      'auth',
      'ci',
      'deploy',
      'deps',
      'infra',
      'plan',
      // design system
      'design',
      'icons',
      'layout',
      'tokens',
      // areas
      'calendars',
      'charts',
      'comments',
      'dashboard',
      'discover',
      'home',
      'lists',
      'media',
      'movies',
      'overlay',
      'people',
      'search',
      'settings',
      'shows',
      'users',
    ]],
  },
};
